### ISSUE TITLE
Modify Parser for For-Loops and If-Statements

### ISSUE THREAD

**Issue by mackncheesiest** [mackncheesiest/ECE474A_Projects#11]
See issue title.

Need to modify Parser to handle new additions/changes in c-like file format

**Comment by kennondmckeever** [comment]
FOR loops can't be preprocessed =(
IF statements can, however. It might make some wires that are only assigned to themselves in the case of nested IFs, though.
Also, I need to merge the parser and the preprocessor so that the preprocessor can add the temporaries as wires of the appropriate size.
Finally, I probably shouldn't have pushed this to the main branch since it breaks main right now...

**Comment by mackncheesiest** [comment]
Tentatively closed in 4e8c8b870a382d1f387ed96d6aaec33fdb985301
